# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d74126472104da28223596ae80851d81e2020425bd611c92b91486bc0dbeb3eddb960a91118e775a04cb58f6b5c8f3077a28e397735084ba99cc6e719d068738

test:
  secret_key_base: 7a09fce514bcb44afa2c65cee309e8204c2ded68f25dde9bd1c7e87a387af53679c3a9baa8bf44fe8d4b5cd97def84f36ee108d92ebc7bab20f6269a9da07a23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
